version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8083:8080"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    depends_on:
      - builder

  builder:
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - .:/geoserver
    command: mvn package -DskipTests
    working_dir: /geoserver/src


