version: '3.8'

services:
  builder:
    build:
      context: ./build
      dockerfile: Dockerfile
    volumes:
      - ./build/output:/build/output
      - ./build/pom.xml:/build/source/pom.xml
    command: >
      sh -c "rm -rf /build/source && \
             git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git /build/source &&
             cd /build/source &&
             mvn clean package && \
             cp target/*.war /build/output"
    
  prod:
    build:
      context: ./prod
      dockerfile: Dockerfile
    ports:
      - "82:80"
    volumes:
      - ./build/output:/usr/local/tomcat/webapps

