#use maven image for build
FROM maven:3.9.5-eclipse-temurin-17 AS builder
RUN git clone https://github.com/geoserver/geoserver.git
WORKDIR /geoserver/src
#build project exclude test
RUN mvn package -DskipTests

