
FROM maven:latest as builder
WORKDIR /app
RUN git clone https://github.com/geoserver/geoserver.git /app
WORKDIR /app/src
RUN mvn clean package -DskipTests

FROM tomcat9:latest
WORKDIR /usr/local/tomcat/webapps/
COPY --from=builder /app/src/web/app/target/*.war ./
RUN rm -rf /usr/local/tomcat/work/* /usr/local/tomcat/temp/*
CMD ["catalina.sh", "run"]