---
  - name: Setup Docker
    hosts: all
    become: yes
    tasks:
      - name: Install packages
        apt:
          update_cache: yes
          name: 
            - git
            - docker.io
            - openjdk-11-jdk
          state: present
  
      - name: Ensure Docker service is running
        service:
          name: docker
          state: started
          enabled: yes
  
  - name: Run build process
    hosts: 130.193.57.224
    become: yes
    tasks:
      - name: git clone repository
        git: 
          repo: https://github.com/geoserver/geoserver.git
          dest: /app
          clone: yes
          update: yes  
          force: no
  
      - name: pull maven image
        docker_image:
          name: maven
          tag: latest
          state: present 
  
      - name: Build WAR file using Maven
        docker_container:
            name: maven_build
            image: maven:latest
            command: mvn clean package -DskipTests
            volumes:
              - /app:/app
            working_dir: /app/src
            state: started
            detach: false
        args:
          creates: /app/src/web/app/target/geoserver.war
  
      - name: Copy war file to production node
        fetch:
          src: /app/src/web/app/target/geoserver.war
          dest: /tmp/
          flat: yes
  
  - name: Run production environment
    hosts: 84.201.151.242
    become: yes
    tasks:
      - name: apt package
        apt:
          name: tomcat9
          state: present
          
      - name: copy war file in prod
        copy: 
          src: /tmp/geoserver.war
          dest: /var/lib/tomcat9/webapps
        become: yes
  
      - name: tomcat started
        service:
          name: tomcat9
          state: started
          enabled: yes
    
  
      - name: Verify application is running
        uri:
          url: http://84.201.151.242:8082/geoserver
          status_code: 200
          validate_certs: no
        register: geo_server_status
  
      - name: Debug application status
        debug:
          var: geo_server_status
  



