---
- name: Setup Docker
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        update_cache: yes
        name: 
          - git
          - docker.io
          - openjdk-11-jdk
        state: present

    - name: docker service is running
      service:
        name: docker
        state: started
        enabled: yes

- name: Run build process
  hosts: build_node
  become: yes
  tasks:
    - name: git clone repository
      git: 
        repo: https://github.com/geoserver/geoserver.git
        dest: /app
        clone: yes
        update: yes  

    - name: Pull maven image 
      docker_image:
        name: maven
        tag: latest
        state: present 

    - name: build war using maven in docker
      shell: |
        docker run --rm \
        -v /app:/app \
        -w /app/src \
        maven:latest mvn clean package -DskipTests
      args:
        creates: /app/src/web/app/target/geoserver.war

    - name: Fetch geoserver.war to the Ansible controller
      fetch:
        src: /app/src/web/app/target/geoserver.war
        dest: /tmp/geoserver.war
        flat: yes
      delegate_to: build_node    

    - name: Copy WAR to production node
      copy:
        src: /tmp/geoserver.war
        dest: /tmp/geoserver.war
      delegate_to: prod_node

- name: Run production
  hosts: prod_node
  become: yes
  tasks:
    - name: Pull tomcat image 
      docker_image:
        name: tomcat
        tag: latest
        state: present

    - name: Run production container
      docker_container:
        name: geo-container
        image: tomcat:latest
        state: started
        volumes:
          - "/tmp/geoserver.war:/usr/local/tomcat/webapps/geoserver.war"
        published_ports:
          - "8082:8080"

    - name: app is running
      uri:
        url: http://<prod_node_IP>:8082/geoserver
        status_code: 200
        validate_certs: no
      register: geo_server_status

    - name: Debug app status
      debug:
        var: geo_server_status 



