---
  - name: Setup Docker
    hosts: all
    become: yes
    tasks:
      - name: Install packages
        apt:
          update_cache: yes
          name: 
            - git
            - docker.io
            - openjdk-11-jdk
          state: present
  
      - name: Ensure Docker service is running
        service:
          name: docker
          state: started
          enabled: yes
  
  - name: Run build process
    hosts: 158.160.149.247
    become: yes
    tasks:
      - name: git clone repository
        git: 
          repo: https://github.com/geoserver/geoserver.git
          dest: /app
          clone: yes
          update: yes  
          force: yes
  
      - name: pull maven image
        docker_image:
          name: maven
          tag: latest
          state: present 

      - name: Check if WAR file exists
        stat:
            path: /app/src/web/app/target/geoserver.war
        register: war_file_exists

      - name: Debug WAR file existence
        debug:
          var: war_file_exists.stat.exists
  
      - name: Build WAR file using Maven
        docker_container:
            name: maven_build
            image: maven:latest
            command: mvn clean package -DskipTests
            volumes:
              - /app:/app
            working_dir: /app/src
            state: started
            detach: false
        when: 
          - not war_file_exists.stat.exists    

      - name: Ensure correct permissions for the WAR file
        file:
          path: /app/src/web/app/target/geoserver.war
          owner: root
          group: root
          mode: '0644'
  
      - name: Copy war file to production node
        fetch:
          src: /app/src/web/app/target/geoserver.war
          dest: /tmp/
          flat: yes
  
  - name: Run production environment
    hosts: 158.160.134.42
    become: yes
    tasks:
      - name: apt package
        apt:
          name: tomcat9
          state: present
          
      - name: copy war file in prod
        copy: 
          src: /tmp/geoserver.war
        dest: /var/lib/tomcat9/webapps/geoserver.war
        
      - name: tomcat started
        service:
          name: tomcat9
          state: started
          enabled: yes    
  
      - name: Verify application is running
        uri:
          url: http://158.160.134.42:8082/geoserver
          status_code: 200
          validate_certs: no
        register: geo_server_status
  
      - name: Debug application status
        debug:
          var: geo_server_status
  



