---
- name: Setup Docker
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        update_cache: yes
        name: docker.io
        state: present
      tags: install

    - name: docker service is running
      service:
        name: docker
        state: started
        enabled: yes

- name: Run build process
  hosts: build_node
  become: yes
  tasks:
    - name: Ensure Java is installed
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Pull maven image 
      docker_image:
        name: maven
        tag: latest
        state: present

    - name: git clone
      git: 
        repo: https://github.com/geoserver/geoserver.git
        dest: /app/
        clone: yes
        update: yes    

    - name: Create build to WAR
      shell: mvn clean package -DskipTests
      args:
        chdir: "/app" 
        register: mvn_output

    - name: Debug Maven output
      debug:
        var: mvn_output.stdout_lines

    - name: Verify target directory exists
      stat:
        path: /app/src/web/app/target/geoserver.war
      register: target_stat

    - name: Fail if WAR file is missing
      fail:
        msg: "geoserver.war file is missing after Maven build!"
      when: not target_stat.stat.exists

    - name: Copy WAR to production node
      synchronize:
        src: /app/src/web/app/target/geoserver.war
        dest: /tmp/geoserver.war
        mode: push
      delegate_to: prod_node

- name: Run production
  hosts: prod_node
  become: yes
  tasks:
    - name: Pull tomcat image 
      docker_image:
        name: tomcat
        tag: latest
        state: present

    - name: Run production container
      docker_container:
        name: geo-container
        image: tomcat:latest
        state: started
        volumes:
          - "/tmp/geoserver.war:/usr/local/tomcat/webapps/geoserver.war"
        published_ports:
          - "8082:8080"

    - name: app is running
      uri:
        url: http://130.193.59.244:8082/geoserver
        status_code: 200
        validate_certs: no
      register: geo_server_status

    - name: Debug app status
      debug:
        var: geo_server_status 



