---
  - name: Setup Docker
    hosts: all
    become: yes
    tasks:
      - name: Install packages
        apt:
          update_cache: yes
          name: 
            - git
            - docker.io
            - openjdk-11-jdk
          state: present
  
      - name: Ensure Docker service is running
        service:
          name: docker
          state: started
          enabled: yes
  
  - name: Run build process
    hosts: 158.160.134.101
    become: yes
    tasks:
      - name: git clone repository
        git: 
          repo: https://github.com/geoserver/geoserver.git
          dest: /app
          clone: yes
          update: yes  
  
      - name: pull maven image
        docker_image:
          name: maven
          tag: latest
          state: present 
  
      - name: build war file using maven in docker
        shell: |
          docker run --rm \
          -v /app:/app \
          -w /app/src \
          maven:latest mvn clean package -DskipTests
        args:
          creates: /app/src/web/app/target/geoserver.war
  
      - name: Copy war file to production node
        synchronize:
          src: /app/src/web/app/target/geoserver.war
          dest: /tmp/geoserver.war
        delegate_to: 51.250.38.179
  
  - name: Run production environment
    hosts: 51.250.38.179
    become: yes
    tasks:
      - name: Pull Tomcat image
        docker_image:
          name: tomcat
          tag: latest
          state: present

      - name: Build custom tomcat image with geoserver
        docker_image:
          path: /tmp
          name: tomcat-geoserver
          tag: latest    
     
      - name: Deploy war file and start container
        docker_container:
          name: geo-container
          image: tomcat-geoserver:latest
          state: started
          published_ports:
            - "8080:8080"
  
      - name: Verify application is running
        uri:
          url: http://51.250.38.179:8080/geoserver
          status_code: 200
          validate_certs: no
        register: geo_server_status
  
      - name: Debug application status
        debug:
          var: geo_server_status
  



