FROM tomcat:9-jre17-temurin-jammy
WORKDIR /usr/local/tomcat/webapps/
#copy geoserver.war
COPY --from=builder /app/src/web/app/target/*.war ./
RUN rm -rf /usr/local/tomcat/work/* /usr/local/tomcat/temp/*
CMD ["catalina.sh", "run"]