version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    ports:
      - "82:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

