#use maven image for build
FROM maven:3.8.8-eclipse-temurin-17 as builder
WORKDIR /app
RUN git clone https://github.com/geoserver/geoserver.git /app
WORKDIR /app/src
#build project exclude test
RUN mvn clean package -DskipTests