
FROM maven:3.8.8-eclipse-temurin-17 as builder
WORKDIR /app
RUN git clone https://github.com/geoserver/geoserver.git /app
WORKDIR /app/src
RUN mvn clean package -DskipTests

FROM tomcat:10.1-jre17-temurin-jammy
WORKDIR /usr/local/tomcat/webapps/
COPY --from=builder /app/src/web/app/target/*.war ./ROOT.war
CMD ["catalina.sh", "run"]