# Use lightweight Tomcat base image
FROM tomcat:9.0-jre17-temurin-jammy
# Set working directory
WORKDIR /usr/local/tomcat/webapps/
# Copy WAR file from builder stage
COPY --from=builder /output/app.war ./ROOT.war
# Start Tomcat
CMD ["catalina.sh", "run"]
