---
- name: setup docker
  hosts: all
  become: yes
  tasks:
    - name: install docker
      ansible.builtin.include: |
        apt update && apt install -y docker.io
      tags: install
- name: run build process
  hosts: build_node
  become: yes
  tasks:
    - name: pull build image from Dockerhub
      ansible.builtin.shell: |
        docker pull 