---
- name: Setup Docker
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        update_cache: yes
        name: docker.io
        state: present
      tags: install

- name: Run build process
  hosts: build_node
  become: yes
  tasks:
    - name: Pull build image from DockerHub
      docker_image:
        name: reg117/geo-build
        tag: latest
        source: pull

    - name: Create build container to extract WAR
      docker_container:
        name: geoserver-build-container
        image: reg117/geo-build:latest
        state: started

    - name: Copy WAR file from container
      command:
        cmd: docker cp geoserver-build-container:/app/geoserver/src/web/app/target/*.war /tmp/geoserver.war

    - name: Remove build container
      docker_container:
        name: geoserver-build-container
        state: absent
        force_kill: true

    - name: Copy WAR to production node
      copy:
        src: /tmp/geoserver.war
        dest: /tmp/geoserver.war
      delegate_to: prod_node

- name: Run production
  hosts: prod_node
  become: yes
  tasks:
    - name: Pull production image from DockerHub
      docker_image:
        name: reg117/geo-prod
        tag: latest
        source: pull

    - name: Run production container
      docker_container:
        name: geo-container
        image: reg117/geo-prod:latest
        state: started
        published_ports:
          - "8082:8080"


