---
- name: setup docker
  hosts: all
  become: yes
  tasks:
    - name: install docker
      ansible.builtin.shell: |
        apt update && apt install -y docker.io
      tags: install

- name: run build process
  hosts: build_node
  become: yes
  tasks:
    - name: pull build image from Dockerhub
      ansible.builtin.shell: |
        docker pull reg117/geo-build:latest

    - name: save war
      ansible.builtin.shell: |
        docker create --name geoserver-build-container reg117/geo-build:latest
        docker cp geoserver-build-container:/app/geoserver/src/target/*.war /tmp/geoserver.war
        docker rm geoserver-build-container

    - name: copy war
      ansible.builtin.copy:
        src: /tmp/geoserver.war
        dest: /tmp/geoserver.war
      delegate_to: prod-node

- name: run prod
  hosts: prod_node
  become: yes
  tasks:
    - name: pull prod image
      ansible.builtin.shell: |
        docker pull reg117/geo-prod:latest

    - name: run prod
      ansible.builtin.shell: |
        docker run -d --name=geo-container -p 8082:8080 reg117/geo-prod:latest

